default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demo_devise_development

test:
  <<: *default
  database: demo_devise_test

production:
  <<: *default
  database: demo_devise_production
  username: demo_devise
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>